"""Add network status tables

Revision ID: 001
Revises: 
Create Date: 2025-03-19 11:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_devices',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('netbox_id', sa.Integer(), nullable=True),
        sa.Column('hostname', sa.String(length=100), nullable=False),
        sa.Column('mgmt_ip', sa.String(length=50), nullable=False),
        sa.Column('platform', sa.String(length=100), nullable=True),
        sa.Column('device_role', sa.String(length=50), nullable=True),
        sa.Column('site', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('netbox_id')
    )
    op.create_index(op.f('ix_network_devices_id'), 'network_devices', ['id'], unique=False)
    op.create_index(op.f('ix_network_devices_netbox_id'), 'network_devices', ['netbox_id'], unique=True)
    
    op.create_table('device_check_results',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('device_id', sa.Integer(), nullable=False),
        sa.Column('check_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('operational_status', sa.String(length=20), nullable=True),
        sa.Column('backup_status', sa.String(length=20), nullable=True),
        sa.Column('snapshot_status', sa.String(length=20), nullable=True),
        sa.Column('critical_alarm', sa.String(length=10), nullable=True),
        sa.Column('raw_output', sa.Text(), nullable=True),
        sa.Column('check_status', sa.String(length=20), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['device_id'], ['network_devices.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_check_results_id'), 'device_check_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_check_results_id'), table_name='device_check_results')
    op.drop_table('device_check_results')
    op.drop_index(op.f('ix_network_devices_netbox_id'), table_name='network_devices')
    op.drop_index(op.f('ix_network_devices_id'), table_name='network_devices')
    op.drop_table('network_devices')
    # ### end Alembic commands ###
